# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aivm/engine/v1/engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aivm/engine/v1/engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61ivm/engine/v1/engine.proto\x12\x0e\x61ivm.engine.v1\"b\n\x10\x45xecutionRequest\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x12\n\ninput_hash\x18\x03 \x01(\t\x12\x12\n\ninput_data\x18\x04 \x01(\t\"b\n\x11\x45xecutionResponse\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\t\x12\x13\n\x0bresult_data\x18\x02 \x01(\t\x12\x13\n\x0boutput_hash\x18\x03 \x01(\t\x12\r\n\x05proof\x18\x04 \x01(\t2\\\n\x08\x41IEngine\x12P\n\x07\x45xecute\x12 .aivm.engine.v1.ExecutionRequest\x1a!.aivm.engine.v1.ExecutionResponse\"\x00\x42\x41Z?github.com/cosmosregistry/chain-minimal/x/aimodule/types/engineb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aivm.engine.v1.engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?github.com/cosmosregistry/chain-minimal/x/aimodule/types/engine'
  _globals['_EXECUTIONREQUEST']._serialized_start=47
  _globals['_EXECUTIONREQUEST']._serialized_end=145
  _globals['_EXECUTIONRESPONSE']._serialized_start=147
  _globals['_EXECUTIONRESPONSE']._serialized_end=245
  _globals['_AIENGINE']._serialized_start=247
  _globals['_AIENGINE']._serialized_end=339
# @@protoc_insertion_point(module_scope)
